version: '3'

services:
    app:
      build: ./app
      expose:
        - "8088"
      volumes:
        - ./app/:/src
    api:
      build: ./api
      expose:
        - "8088"
      volumes:
        - ./api/:/src
      environment:
        - NODE_ENV=DEV
      ports:
        - "9229:9229" #for inspector
    nginx:
      build: ./nginx
      links:
        - app
        - api
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "8088:80"